services:
  - type: web
    name: your-app-name
    env: ruby
    plan: free
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec rails server -b 0.0.0.0 -p $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-database-name
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: your-database-name
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: your-database-name
          property: password
      - key: DATABASE_HOST
        fromDatabase:
          name: your-database-name
          property: host
      - key: DATABASE_NAME
        fromDatabase:
          name: your-database-name
          property: database
